import tkinter as tk 

window = tk.Tk()
window.title("tk")
window.geometry("650x300")
text=tk.StringVar()

dogphoto = tk.PhotoImage(file="dog.png")
label1 = tk.Label(window, image=dogphoto)
label2 = tk.Label(window,text="Name")
label3 = tk.Label(window,text="Type")
label4 = tk.Label(window,text="Breed")
label5 = tk.Label(window,text="Owner")
label6 = tk.Label(window,text="Birthdate")
box2= tk.Entry(window, textvariable=text)
box3= tk.Entry(window, textvariable=text)
box4= tk.Entry(window, textvariable=text)
box5= tk.Entry(window, textvariable=text)
box6= tk.Entry(window, textvariable=text)
but1= tk.Button(window,text="<Previous")
but2= tk.Button(window,text="Save Entry")
but3= tk.Button(window,text="Next>")
but4= tk.Button(window,text="Search by Name")
box7= tk.Entry(window, textvariable=text)
label7= tk.Label(window,text="Client Database")

label1.grid(row=0,column=0,padx=5, pady=8)
label2.grid(row=1,column=0, padx=5, pady=8)
box2.grid(row=2,column=0,padx=5, pady=8)
but1.grid(row=3,column=0, padx=5, pady=8)
label3.grid(row=1, column=1,padx=5, pady=8)
box3.grid(row=2, column=1, padx=5, pady=8)
label7.grid(row=0, column=2, padx=5, pady=8)
label4.grid(row=1, column=2, padx=5, pady=8)
box4.grid(row=2,column=2, padx=5, pady=8)
but2.grid(row=3,column=2, padx=5, pady=8)
but4.grid(row=0, column=3, padx=5, pady=8)
label5.grid(row=1, column=3,padx=5, pady=8)
box5.grid(row=2, column=3, padx=5, pady=8)
box7.grid(row=0,column=4, padx=5, pady=8)
label6.grid(row=1,column=4, padx=5, pady=8)
box6.grid(row=2, column=4, padx=5, pady=8)
but3.grid(row=3, column=4, padx=5, pady=8)
window.mainloop()